Etape 1: Creation du DataSet

In [43]:
import pandas 
import numpy as np
import matplotlib.pyplot as plt


df_3features=pandas.read_csv("./datasets/Stress_temperature_step_humidity.csv", sep =',')
df_health=pandas.read_csv("./datasets/Sleep_health.csv", sep =',')
df_sleep=pandas.read_csv("./datasets/sayopillow/SaYoPillow.csv", sep =',')

df_health.drop(["Occupation","Blood Pressure"], axis = 1, inplace=True)





In [44]:
#df_health.drop( labels="Person ID", axis = 1, inplace= True)
df_health.drop( labels="BMI Category", axis = 1, inplace = True)

In [23]:
df_health.iloc[:20]

Gender  Age  Sleep Duration  Quality of Sleep  Physical Activity Level  \
0     Male   27             6.1                 6                       42   
1     Male   28             6.2                 6                       60   
2     Male   28             6.2                 6                       60   
3     Male   28             5.9                 4                       30   
4     Male   28             5.9                 4                       30   
5     Male   28             5.9                 4                       30   
6     Male   29             6.3                 6                       40   
7     Male   29             7.8                 7                       75   
8     Male   29             7.8                 7                       75   
9     Male   29             7.8                 7                       75   
10    Male   29             6.1                 6                       30   
11    Male   29             7.8                 7                       75   
12    Male   29             6.1                 6                       30   
13    Male   29             6.0                 6                       30   
14    Male   29             6.0                 6                       30   
15    Male   29             6.0                 6                       30   
16  Female   29             6.5                 5                       40   
17    Male   29             6.0                 6                       30   
18  Female   29             6.5                 5                       40   
19    Male   30             7.6                 7                       75   

    Stress Level  Heart Rate  Daily Steps Sleep Disorder  
0              6          77         4200            NaN  
1              8          75        10000            NaN  
2              8          75        10000            NaN  
3              8          85         3000    Sleep Apnea  
4              8          85         3000    Sleep Apnea  
5              8          85         3000       Insomnia  
6              7          82         3500       Insomnia  
7              6          70         8000            NaN  
8              6          70         8000            NaN  
9              6          70         8000            NaN  
10             8          70         8000            NaN  
11             6          70         8000            NaN  
12             8          70         8000            NaN  
13             8          70         8000            NaN  
14             8          70         8000            NaN  
15             8          70         8000            NaN  
16             7          80         4000    Sleep Apnea  
17             8          70         8000    Sleep Apnea  
18             7          80         4000       Insomnia  
19             6          70         8000            NaN

In [15]:

#11 features 
print(df_health["Sleep Disorder"].unique())
print(df_health["Sleep Duration"].unique())
print(df_health["Quality of Sleep"].unique())
print(df_health["Stress Level"].unique())
print(df_health["Physical Activity Level"].unique())
print(df_health["BMI Category"].unique())
print(df_health["Heart Rate"].unique())
print(df_health["Daily Steps"].unique())

[nan 'Sleep Apnea' 'Insomnia']
[6.1 6.2 5.9 6.3 7.8 6.  6.5 7.6 7.7 7.9 6.4 7.5 7.2 5.8 6.7 7.3 7.4 7.1
 6.6 6.9 8.  6.8 8.1 8.3 8.5 8.4 8.2]
[6 4 7 5 8 9]
[6 8 7 4 3 5]
[42 60 30 40 75 35 45 50 32 70 80 55 90 47 65 85]
['Overweight' 'Normal' 'Obese' 'Normal Weight']
[77 75 85 82 70 80 78 69 72 68 76 81 65 84 74 67 73 83 86]
[ 4200 10000  3000  3500  8000  4000  4100  6800  5000  7000  5500  5200
  5600  3300  4800  7500  7300  6200  6000  3700]


### DESCRIPTION DES FEATURES ###  
Gender : Male or Female (**Initial Data from individual**)  
Age : Age of the induvidual (**Initial Data from individual**)  
Sleep Duration : in hours decimal (**Watch**)  
Quality of Sleep : Assessed on a 0-10 scale (**assessed by questionnaire**)  
irritation level : Assessed on a 0-10 scale (**assessed by questionnaire**)  
Control level : Assessed on a 0-10 scale (**assessed by questionnaire**)  
Emotion Control level : Assessed on a 0-10 scale (**assessed by questionnaire**)  
Physical Activity Level : number of minutes spent exercising during the day (**watch or questionnaire**)  
Heart Rate : BPM nominale (**Initial Data from individual**)  
Heart mean : mean of BPM during the day (**watch**)  
Daily Steps : number of steps during the day (**watch**)  
Sleep Disorder : [Regular, Sleep Apnea, Insomnia'] (**Initial Data from individual**)   
Stress Level : Target feature (1 - not stressed, 2 - regular, 3 - stressed)    

In [45]:
df_health['Irritation Level'] =(( df_health['Stress Level'] + (10 - df_health['Quality of Sleep']))  // 2 + np.random.choice([-2, -1, 0, 1, 2], len(df_health)))

In [46]:
df_health['Control'] =( (10 - df_health['Stress Level'])  + np.random.choice([-2, -1, 0, 1, 2], len(df_health)))

In [47]:
df_health['Emotion Control Level'] =(( (df_health['Physical Activity Level'] / 9)  + (10 - df_health['Stress Level']))  // 2 + np.random.choice([-2, -1, 0, 1, 2], len(df_health)))

In [48]:

df_health['Mean Heart Rate'] = (
    df_health['Heart Rate'] +
    np.maximum(5, ((df_health['Stress Level'] - 5) + ((df_health['Physical Activity Level']) * 5 / df_health['Physical Activity Level'].max()))) +
    np.random.choice([-2, -1, 0, 1, 2], len(df_health))
)

In [49]:
df_health['Gender'] = df_health['Gender'].map({'Male': 0, 'Female': 1})
df_health['Sleep Disorder'] = df_health['Sleep Disorder'].map({'Sleep Apnea' : 1, 'Insomnia': 2})
df_health.fillna(0, inplace=True)

In [52]:
df_health.describe()
df_health.drop('Person ID', axis = 1)

Gender  Age  Sleep Duration  Quality of Sleep  Physical Activity Level  \
0         0   27             6.1                 6                       42   
1         0   28             6.2                 6                       60   
2         0   28             6.2                 6                       60   
3         0   28             5.9                 4                       30   
4         0   28             5.9                 4                       30   
..      ...  ...             ...               ...                      ...   
369       1   59             8.1                 9                       75   
370       1   59             8.0                 9                       75   
371       1   59             8.1                 9                       75   
372       1   59             8.1                 9                       75   
373       1   59             8.1                 9                       75   

     Stress Level  Heart Rate  Daily Steps  Sleep Disorder  Irritation Level  \
0               6          77         4200             0.0                 3   
1               8          75        10000             0.0                 7   
2               8          75        10000             0.0                 8   
3               8          85         3000             1.0                 6   
4               8          85         3000             1.0                 7   
..            ...         ...          ...             ...               ...   
369             3          68         7000             1.0                 4   
370             3          68         7000             1.0                 4   
371             3          68         7000             1.0                 2   
372             3          68         7000             1.0                 0   
373             3          68         7000             1.0                 4   

     Control  Emotion Control Level  Mean Heart Rate  
0          3                    2.0        82.000000  
1          4                    4.0        80.333333  
2          1                    3.0        81.333333  
3          3                    0.0        92.000000  
4          3                    3.0        92.000000  
..       ...                    ...              ...  
369        6                    6.0        74.000000  
370        9                    9.0        74.000000  
371        5                    5.0        75.000000  
372        9                    6.0        71.000000  
373        5                    6.0        73.000000  

[374 rows x 13 columns]

In [53]:

df_health.to_csv('Premier_DataFrama.csv', index=False)

In [4]:
df_3features.drop(["Step_count", "Temperature"], axis = 1, inplace=True)

In [2]:
df_health.head()



Person ID Gender  Age  Sleep Duration  Quality of Sleep  \
0          1   Male   27             6.1                 6   
1          2   Male   28             6.2                 6   
2          3   Male   28             6.2                 6   
3          4   Male   28             5.9                 4   
4          5   Male   28             5.9                 4   

   Physical Activity Level  Stress Level BMI Category  Heart Rate  \
0                       42             6   Overweight          77   
1                       60             8       Normal          75   
2                       60             8       Normal          75   
3                       30             8        Obese          85   
4                       30             8        Obese          85   

   Daily Steps Sleep Disorder  
0         4200            NaN  
1        10000            NaN  
2        10000            NaN  
3         3000    Sleep Apnea  
4         3000    Sleep Apnea

In [6]:
valeurs_sleep_disorter = df_health['Sleep Disorder'].unique()

# Affiche les valeurs uniques
print(valeurs_sleep_disorter)

[nan 'Sleep Apnea' 'Insomnia']


In [7]:
valeurs_stress_lvl = df_health['Stress Level'].unique()

print(valeurs_stress_lvl)
df_health["Stress Level"] = df_health["Stress Level"].replace({ 3 : 0, 4 : 0, 5 : 1, 6 : 1, 7 : 2, 8 : 2})


[6 8 7 4 3 5]


In [9]:
df_health.head()

Person ID Gender  Age  Sleep Duration  Quality of Sleep  \
0          1   Male   27             6.1                 6   
1          2   Male   28             6.2                 6   
2          3   Male   28             6.2                 6   
3          4   Male   28             5.9                 4   
4          5   Male   28             5.9                 4   

   Physical Activity Level  Stress Level BMI Category  Heart Rate  \
0                       42             1   Overweight          77   
1                       60             2       Normal          75   
2                       60             2       Normal          75   
3                       30             2        Obese          85   
4                       30             2        Obese          85   

   Daily Steps Sleep Disorder  
0         4200            NaN  
1        10000            NaN  
2        10000            NaN  
3         3000    Sleep Apnea  
4         3000    Sleep Apnea

In [10]:
df_3features.head()

Humidity  Stress_Level
0     21.33             1
1     21.41             1
2     27.12             2
3     27.64             2
4     10.87             0

In [11]:
#df_stress = pandas.merge(df_3features, df_health, left_on='Stress_Level', right_on='Stress Level', how='inner')

df_stress.iloc[:100]

Humidity  Stress_Level  Person ID Gender  Age  Sleep Duration  \
0      21.33             1          1   Male   27             6.1   
1      21.33             1          8   Male   29             7.8   
2      21.33             1          9   Male   29             7.8   
3      21.33             1         10   Male   29             7.8   
4      21.33             1         12   Male   29             7.8   
..       ...           ...        ...    ...  ...             ...   
95     21.33             1        208   Male   43             7.7   
96     21.33             1        209   Male   43             7.7   
97     21.33             1        210   Male   43             7.8   
98     21.33             1        211   Male   43             7.7   
99     21.33             1        212   Male   43             7.8   

    Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                  6                       42             1   Overweight   
1                  7                       75             1       Normal   
2                  7                       75             1       Normal   
3                  7                       75             1       Normal   
4                  7                       75             1       Normal   
..               ...                      ...           ...          ...   
95                 8                       90             1       Normal   
96                 8                       90             1       Normal   
97                 8                       90             1       Normal   
98                 8                       90             1       Normal   
99                 8                       90             1       Normal   

    Heart Rate  Daily Steps Sleep Disorder  
0           77         4200            NaN  
1           70         8000            NaN  
2           70         8000            NaN  
3           70         8000            NaN  
4           70         8000            NaN  
..         ...          ...            ...  
95          70         8000            NaN  
96          70         8000            NaN  
97          70         8000            NaN  
98          70         8000            NaN  
99          70         8000            NaN  

[100 rows x 13 columns]